### ISSUE TITLE
index.html "About APP" section

### ISSUE THREAD

**Issue by jbradley84** [abbygraves/awkward-party-pal#3]
## Description

AS AN Awkward Party Pal noob
I WANT to read something that tells me the basics of the Awkward Party Pal app
SO THAT I understand the purpose of the app, and I am excited to use it

I WANT to see a funny yet relatable meme
SO THAT I know the app is hip and trendy

**Comment by abbygraves** [comment]
- Added text content to describe website and our purpose
- Added an image
