### ISSUE TITLE
index.html "Party Pals" Form section

### ISSUE THREAD

**Issue by jbradley84** [abbygraves/awkward-party-pal#4]
## Description

AS AN Awkward Party Pal user
I WANT a form where I can
* Input the name of a person I know will be at the party
* Input information I know about that person's likes/dislikes

SO THAT I am prepared to interact with that person at the party

I WANT the form input sections to have placeholder values with sample text
SO THAT app users can visualize how the form inputs are intended to be used

**Comment by JulianHeaney** [comment]
Wrote js code for user to save name/identifier and information.
