### ISSUE TITLE
Tailwind CSS

### ISSUE THREAD

**Issue by jbradley84** [abbygraves/awkward-party-pal#7]
## Description

AS AN Awkward Party Pal app developer
I WANT to use Tailwind and CSS to develop the overall look of Awkward Party Pal
SO THAT other developers can plug my design elements into their build projects

**Comment by abbygraves** [comment]
- Used Tailwinds CSS to created columns and rows for the general layout of the webpage
- Used Tailwinds CSS to assign background colors to majority of the webpage's elements
- Used Tailwinds CSS to design a basic form 
- Used Tailwinds CSS to design basic cards

**Comment by abbygraves** [comment]
- Using to Tailwinds CSS to create responsive layouts
- Using Tailwinds CSS for hover elements on buttons
