### ISSUE TITLE
event.html Dynamic "Party Pal" profile cards

### ISSUE THREAD

**Issue by jbradley84** [abbygraves/awkward-party-pal#9]
## Description

AS AN Awkward Party Pal app developer
I WANT to dynamically create Party Pal profile cards using data maintained in localStorage
SO THAT when app users access event.html, Party Pal profile cards automatically appear on the page

I WANT Party Pal profile cards to be editable 
SO THAT app users can update Party Pal profile info 

I WANT to be able to alter a Party Pal profile card in some way that indicates I have already interacted with that Party Pal
SO THAT app users can track their progress working the room

**Comment by JulianHeaney** [comment]
Wrote js code to facilitate the creation of profile cards. Profile cards generate of event.html. They can be deleted when the party is over.
